version: '3'

services:
  frontend:
    image: frontend
    build: ./frontend
    ports:
      - 4000:4201
    depends_on:
      - backend
  backend:
    image: backend
    build: ./backend
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - 27017:27017