version: '3.7'

services:
  frontend:
    image: frontend
    ports:
      - 4000:4201
    depends_on:
      - backend
  backend:
    image: backend
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mongo:latest